### ISSUE TITLE
Cannot find the trained play2vec model in the model_1 folder.

### ISSUE THREAD

**Issue by mcjeong95** [zhengwang125/SimPlay#1]
Hi Zheng, I'd like to applaud for your great research and also releasing code as public!

I'm trying to apply your work on my own dataset, however I cannot find the trained play2vec model(`trained_model.ckpt`) in the `model_1` folder, even though README says this repo provides it.

Where can I find the checkpoint file?

**Comment by zhengwang125** [comment]
Hi, Thank you, I can the model at my side. 
![image](https://user-images.githubusercontent.com/8544661/196228894-68a5fe1f-c333-418f-bebe-a8c48c9c5484.png)

**Comment by mcjeong95** [comment]
Oh, I got it. 

I'll try it again, Thank you! :)
